changed code a little

diff --git a/evals/submit b/evals/submit
--- a/evals/submit
+++ b/evals/submit
@@ -2,7 +2,20 @@
 
 ROLL=2018101012_2018101019_2018111010_2018111022
 
-zip "$ROLL.zip" trie_comp.cpp kvStore.cpp || { echo "Error in making zip"; exit 1; }
+function backup {
+    echo "Backing up kvStore..."
+    cp kvStore.cpp kvStore.cpp.bak
+}
+
+function restore {
+    echo "Restoring kvStore..."
+    cp kvStore.cpp.bak kvStore.cpp
+}
+
+backup
+cat trie_comp.cpp <( sed '1,3d' kvStore.cpp ) > kvStore.cpp
+
+zip "$ROLL.zip" kvStore.cpp && { echo "zipped files"; restore; } || { echo "Error in making zip"; restore; exit 1; }
 
 echo "Generating mail..."
 mpack -s "$ROLL" -o mail ./2018101012_2018101019_2018111010_2018111022.zip || { echo "Error in generating mail"; exit 1; }
